services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "8541:5432"
    environment:
      POSTGRES_USER: "pg"
      POSTGRES_DB: "tests"
      POSTGRES_PASSWORD: "password"
volumes:
  db:
    driver: local